# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: cjbcrazy's website
email: chris@please-dont-email-me.com
description: > # this means to ignore newlines until "baseurl:"
  Hobbyist website for content created by Chris Bentley.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cjbcrazy.com" # the base hostname & protocol for your site
twitter_username: cjbcrazy
github_username:  chrisbentley
steam_username: cjbcrazy

# Build settings
markdown: kramdown
